"""
============================================================================
FILE: mermaid_validator.py
LOCATION: server/utils/mermaid_validator.py
============================================================================
PURPOSE:
    Validates Mermaid diagram syntax to detect parsing errors before rendering.
ROLE IN PROJECT:
    Utility module to check Mermaid code blocks generated by AI agents.
    - Prevents rendering errors in the client UI
    - Enables agent retry logic on syntax errors
KEY COMPONENTS:
    - validate_mermaid_code: Entrypoint to validate a Mermaid diagram
    - validate_flowchart_line: Validates a single line of a flowchart diagram
    - parse_node_def: Parses and validates a single node definition
DEPENDENCIES:
    - External: None
    - Internal: None
USAGE:
    from server.utils.mermaid_validator import validate_mermaid_code
    error = validate_mermaid_code(chart_text)
    if error:
        # handle retry
============================================================================
"""

import re
from typing import Optional, List, Tuple


def split_by_regex_outside_quotes(s: str, pattern: re.Pattern) -> List[str]:
    """Splits string s by pattern, ignoring matches inside double quotes."""
    in_quotes = [False] * len(s)
    current_in_quotes = False
    escaped = False
    for idx, char in enumerate(s):
        if escaped:
            in_quotes[idx] = current_in_quotes
            escaped = False
            continue
        if char == "\\":
            in_quotes[idx] = current_in_quotes
            escaped = True
            continue
        if char == '"':
            current_in_quotes = not current_in_quotes
        in_quotes[idx] = current_in_quotes

    matches = list(pattern.finditer(s))
    valid_matches = []
    for m in matches:
        start, end = m.span()
        if not any(in_quotes[i] for i in range(start, end)):
            valid_matches.append((start, end))

    parts = []
    last_idx = 0
    for start, end in valid_matches:
        parts.append(s[last_idx:start])
        last_idx = end
    parts.append(s[last_idx:])

    return parts


def split_outside_quotes(s: str, delimiters: List[str]) -> List[str]:
    """Splits string s by any delimiter, ignoring matches inside double quotes."""
    parts = []
    current_part = []
    in_quotes = False
    escaped = False

    i = 0
    n = len(s)
    while i < n:
        char = s[i]

        if escaped:
            current_part.append(char)
            escaped = False
            i += 1
            continue

        if char == "\\":
            current_part.append(char)
            escaped = True
            i += 1
            continue

        if char == '"':
            in_quotes = not in_quotes
            current_part.append(char)
            i += 1
            continue

        if not in_quotes:
            matched_delim = None
            for delim in delimiters:
                if s.startswith(delim, i):
                    matched_delim = delim
                    break

            if matched_delim:
                parts.append("".join(current_part))
                current_part = []
                i += len(matched_delim)
                continue

        current_part.append(char)
        i += 1

    parts.append("".join(current_part))
    return parts


def parse_node_def(s: str) -> Tuple[bool, str]:
    """Parses a single node definition from string `s`.

    Returns (is_valid, remaining_string).
    """
    s = s.strip()
    if not s:
        return False, "Empty node definition"

    id_match = re.match(r"^([a-zA-Z0-9_-]+)", s)
    if not id_match:
        return False, f"Invalid node ID format in: {s}"

    node_id = id_match.group(1)
    rest = s[id_match.end() :].strip()

    if not rest:
        return True, ""

    shape_pairs = [
        ("([", "])"),
        ("[[", "]]"),
        ("[(", ")]"),
        ("((", "))"),
        ("{{", "}}"),
        ("[/", "/]"),
        ("[\\", "\\]"),
        ("[", "]"),
        ("(", ")"),
        ("{", "}"),
        (">", "]"),
    ]

    open_shape = None
    close_shape = None
    for op, cl in shape_pairs:
        if rest.startswith(op):
            open_shape = op
            close_shape = cl
            break

    if not open_shape:
        return False, f"Unexpected characters after node ID '{node_id}': '{rest}'"

    content = rest[len(open_shape) :]
    esc_close = re.escape(close_shape)

    if content.startswith('"'):
        match = re.match(r'^"(.*?)"\s*' + esc_close + r"\s*$", content)
        if match:
            label_text = match.group(1)
            unescaped_quotes = re.findall(r'(?<!\\)"', label_text)
            if unescaped_quotes:
                return False, f"Unescaped double quotes inside label in: {s}"
            return True, ""
        else:
            return False, f"Unmatched double quotes or closing bracket '{close_shape}' in: {s}"
    else:
        match = re.match(r"^(.*?)" + esc_close + r"\s*$", content)
        if match:
            label_text = match.group(1)
            if '"' in label_text:
                return False, f"Double quotes found in unquoted label in: {s}"
            return True, ""
        else:
            return False, f"Missing closing bracket '{close_shape}' in: {s}"


def validate_flowchart_line(line: str) -> Optional[str]:
    """Validates a single line of a flowchart or graph diagram."""
    line = line.strip()
    if not line or line.startswith("%%"):
        return None
    if line == "end":
        return None
    if line.startswith("subgraph"):
        unescaped_quotes = re.findall(r'(?<!\\)"', line)
        if len(unescaped_quotes) % 2 != 0:
            return f"Unmatched double quotes in subgraph definition: {line}"
        return None

    if any(
        line.startswith(keyword)
        for keyword in [
            "direction",
            "style",
            "classDef",
            "class",
            "click",
            "linkStyle",
        ]
    ):
        return None

    conn_pattern = re.compile(
        r'(?:-->\|.*?\||---\|.*?\||==>\|.*?\||-\.-\|.*?\||--\s*".*?"\s*-->|--\s*[^-\s]+\s*-->|--+>|--+|==+>|==+|-\.-+>|-\.-+)'
    )
    segments = split_by_regex_outside_quotes(line, conn_pattern)

    for segment in segments:
        segment = segment.strip()
        if not segment:
            continue
        node_parts = split_outside_quotes(segment, ["&"])
        for part in node_parts:
            part = part.strip()
            if not part:
                continue
            is_valid, err_msg = parse_node_def(part)
            if not is_valid:
                return f"Invalid node/syntax: {err_msg}"

    return None


def validate_general_mermaid_line(line: str) -> Optional[str]:
    """Loose validation for non-flowchart diagrams."""
    line = line.strip()
    if not line or line.startswith("%%"):
        return None
    unescaped_quotes = re.findall(r'(?<!\\)"', line)
    if len(unescaped_quotes) % 2 != 0:
        return f"Unmatched double quotes in line: {line}"
    return None


def validate_mermaid_code(code: str) -> Optional[str]:
    """Validates a Mermaid diagram code block.

    Returns None if valid, or an error message if invalid.
    """
    lines = [line.strip() for line in code.split("\n")]
    lines = [line for line in lines if line]

    if not lines:
        return None

    # Find the header line (first non-comment line)
    header_idx = -1
    for idx, line in enumerate(lines):
        if not line.startswith("%%"):
            header_idx = idx
            break

    if header_idx == -1:
        return None  # Only comments or empty

    header = lines[header_idx].lower()
    is_flowchart = header.startswith("graph") or header.startswith("flowchart")

    for i, line in enumerate(lines):
        if i == header_idx:
            continue  # Skip header line from node validation

        if is_flowchart:
            err = validate_flowchart_line(line)
            if err:
                return f"Line {i+1}: {err}"
        else:
            err = validate_general_mermaid_line(line)
            if err:
                return f"Line {i+1}: {err}"

    return None

