"""
============================================================================
FILE: test_generator_agent.py
LOCATION: server/tests/test_generator_agent.py
============================================================================
PURPOSE:
    Unit tests for GeneratorAgent class and system prompt. Validates agent
    role, educational content generation, system prompt structure, and
    generate_explanation() wiring to instructor client.
ROLE IN PROJECT:
    Ensures the generator agent produces correctly structured educational
    content and injects narrative context between topics.
    - Covers system prompt structure and 5E pedagogical framework
    - Validates context injection for narrative continuity
KEY COMPONENTS:
    - TestGeneratorAgentRole: Agent role and prompt structure tests
    - TestGeneratorAgentExplanation: generate_explanation wiring tests
DEPENDENCIES:
    - External: unittest, unittest.mock
    - Internal: server.agents.generator, server.schemas.learning
USAGE:
    ```python
    python -m unittest server.tests.test_generator_agent
    ```
============================================================================
"""

# test_generator_agent.py
# Unit tests for the Generator Agent

# Tests GeneratorAgent initialization, system prompt structure, and
# the generate_explanation method with mocked LLM responses.
# Validates educational content guidelines and context injection.

# @see: server/agents/generator.py - GeneratorAgent implementation
# @note: Uses unittest.mock to avoid actual API calls

import unittest
from unittest.mock import AsyncMock, patch

from server.agents.generator import (
    GENERATOR_SYSTEM_PROMPT,
    GeneratedContent,
    GeneratorAgent,
    generator_agent,
)
from server.schemas.learning import TopicNode
from server.schemas.llm import LLMContext


def _make_mock_topic(index: int = 0) -> TopicNode:
    """Create a mock TopicNode for testing."""
    return TopicNode(
        index=index,
        title=f"Test Topic {index}",
        summary_for_context=f"Summary for test topic {index}",
        key_terms=[f"term-{index}a", f"term-{index}b"],
    )


def _make_mock_content() -> GeneratedContent:
    """Create a mock GeneratedContent for testing."""
    return GeneratedContent(
        content_markdown="""# Test Topic

This is a longer mock content that meets the minimum 300 character requirement. 
It contains multiple paragraphs and provides enough text to satisfy the validation 
constraints we've added to ensure quality content generation.

**Key Concept**: Understanding this concept is fundamental to the topic.

The content should be substantive enough to represent real educational material that 
would be generated by the agent in actual use cases.""",
        key_takeaways=[
            "First key takeaway",
            "Second key takeaway",
            "Third important idea",
        ],
    )


class TestGeneratorAgentRole(unittest.TestCase):
    """Tests for GeneratorAgent role verification.

    Objective: Verify the agent role is correctly set to "generator"
    and not confused with other agent roles.
    """

    def test_agent_role(self) -> None:
        """Positive test: Verify the agent role is 'generator'.

        This test meets the objective by ensuring the GeneratorAgent
        is correctly identified by its role for model config lookup.
        """
        agent = GeneratorAgent()
        self.assertEqual(agent.role, "generator")

    def test_singleton_role(self) -> None:
        """Positive test: Verify the singleton instance has correct role.

        This test meets the objective by validating the module-level
        singleton is properly initialized with the 'generator' role.
        """
        self.assertEqual(generator_agent.role, "generator")

    def test_agent_role_is_not_planner(self) -> None:
        """Negative test: Verify role is NOT 'planner'.

        This test meets the objective by ensuring the GeneratorAgent
        is not misconfigured with another agent's role.
        """
        agent = GeneratorAgent()
        self.assertNotEqual(agent.role, "planner")

    def test_agent_role_is_not_quizzer(self) -> None:
        """Negative test: Verify role is NOT 'quizzer'.

        This test meets the objective by ensuring the GeneratorAgent
        is not misconfigured with another agent's role.
        """
        agent = GeneratorAgent()
        self.assertNotEqual(agent.role, "quizzer")


class TestGeneratorSystemPrompt(unittest.TestCase):
    """Tests for GeneratorAgent system prompt structure.

    Objective: Verify the system prompt contains all required
    guidelines for educational content creation.
    """

    def test_system_prompt_contains_role_definition(self) -> None:
        """Positive test: Check educational content creator role in prompt.

        This test meets the objective by verifying the prompt defines
        the agent's role as an educational content creator.
        """
        agent = GeneratorAgent()
        prompt = agent.system_prompt

        # Role definition should be present
        self.assertIn("educational content creator", prompt.lower())

    def test_system_prompt_contains_markdown_formatting(self) -> None:
        """Positive test: Check Markdown formatting requirements in prompt.

        This test meets the objective by verifying the prompt includes
        instructions for proper Markdown formatting of content.
        """
        agent = GeneratorAgent()
        prompt = agent.system_prompt

        # Markdown formatting should be mentioned
        self.assertIn("Markdown", prompt)
        self.assertIn("format", prompt.lower())

        # Specific formatting elements should be mentioned
        self.assertIn("headers", prompt.lower())
        self.assertIn("bold", prompt.lower())

    def test_system_prompt_contains_reading_time_target(self) -> None:
        """Positive test: Check 2-3 minute reading time target in prompt.

        This test meets the objective by verifying the prompt specifies
        the target reading time for generated content.
        """
        agent = GeneratorAgent()
        prompt = agent.system_prompt

        # Reading time target should be present
        self.assertIn("2-3 minute", prompt.lower())

        # Word count guidance should also be present
        self.assertIn("300", prompt)
        self.assertIn("500", prompt)

    def test_system_prompt_contains_engagement_guidelines(self) -> None:
        """Positive test: Check engagement/enthusiasm guidelines in prompt.

        This test meets the objective by verifying the prompt includes
        instructions for creating engaging, enthusiastic content.
        """
        agent = GeneratorAgent()
        prompt = agent.system_prompt

        # Engagement guidelines should be present
        self.assertIn("engag", prompt.lower())  # engaging, engagement
        self.assertIn("enthusias", prompt.lower())  # enthusiasm, enthusiastic

    def test_system_prompt_contains_context_injection(self) -> None:
        """Positive test: Check context injection instructions in prompt.

        This test meets the objective by verifying the prompt explains
        how to use prev/next topic context for narrative coherence.
        """
        agent = GeneratorAgent()
        prompt = agent.system_prompt

        # Context injection should be explained
        self.assertIn("Context", prompt)
        self.assertIn("Previous Topic", prompt)
        self.assertIn("Next Topic", prompt)

        # Bridging and foreshadowing should be mentioned
        self.assertIn("bridge", prompt.lower())
        self.assertIn("foreshadow", prompt.lower())

    def test_system_prompt_contains_key_takeaways(self) -> None:
        """Positive test: Check key takeaways requirement in prompt.

        This test meets the objective by verifying the prompt instructs
        the agent to generate key takeaways.
        """
        agent = GeneratorAgent()
        prompt = agent.system_prompt

        # Key takeaways should be mentioned
        self.assertIn("key takeaways", prompt.lower())


class TestGeneratorPromptQuality(unittest.TestCase):
    """Tests for prompt engineering quality."""

    def test_prompt_constant_exists(self) -> None:
        """Verify GENERATOR_SYSTEM_PROMPT is exported and substantive."""
        self.assertIsInstance(GENERATOR_SYSTEM_PROMPT, str)
        self.assertGreater(len(GENERATOR_SYSTEM_PROMPT), 500)

    def test_prompt_has_pedagogical_framework(self) -> None:
        """Check that a pedagogical model is mentioned."""
        # The prompt uses the 5E model
        self.assertIn("5E", GENERATOR_SYSTEM_PROMPT)

    def test_prompt_has_example_structure(self) -> None:
        """Check that example content structure is provided."""
        self.assertIn("Example", GENERATOR_SYSTEM_PROMPT)
        self.assertIn("```", GENERATOR_SYSTEM_PROMPT)  # Code block example


class TestGeneratorAgentGenerate(unittest.TestCase):
    """Tests for GeneratorAgent.generate_explanation() wiring.

    Objective: Verify generate_explanation() correctly calls the
    underlying instructor client with proper arguments.
    """

    @patch(
        "server.agents.base.instructor_client.create_structured",
        new_callable=AsyncMock,
    )
    def test_generate_explanation_calls_instructor_client(
        self, mock_create: AsyncMock
    ) -> None:
        """Positive test: Verify generate_explanation() -> instructor_client wiring.

        This test meets the objective by mocking the instructor client
        and verifying it receives the correct arguments.
        """
        import asyncio

        mock_content = _make_mock_content()
        mock_create.return_value = mock_content

        agent = GeneratorAgent()
        topic = _make_mock_topic(index=1)

        result = asyncio.run(
            agent.generate_explanation(
                topic=topic,
                prev_summary="Previous topic summary",
                next_summary="Next topic summary",
                llm_context=LLMContext(api_key="test-key"),
            )
        )

        # Verify instructor_client.create_structured was called
        mock_create.assert_called_once()

        # Verify the call arguments include role and response_model
        call_kwargs = mock_create.call_args.kwargs
        self.assertEqual(call_kwargs["role"], "generator")
        self.assertEqual(call_kwargs["response_model"], GeneratedContent)

        # Verify messages contain topic information
        messages = call_kwargs["messages"]
        self.assertEqual(len(messages), 1)
        self.assertEqual(messages[0]["role"], "user")
        self.assertIn("Test Topic 1", messages[0]["content"])

        # Verify system prompt was passed
        self.assertIn("system_prompt", call_kwargs)

        # Verify result
        self.assertEqual(result.content_markdown, mock_content.content_markdown)
        self.assertEqual(len(result.key_takeaways), 3)

    @patch(
        "server.agents.base.instructor_client.create_structured",
        new_callable=AsyncMock,
    )
    def test_context_injection_includes_prev_summary(
        self, mock_create: AsyncMock
    ) -> None:
        """Positive test: Verify prev_summary is included in user message.

        This test meets the objective by checking that previous topic
        context is properly injected for narrative bridging.
        """
        import asyncio

        mock_content = _make_mock_content()
        mock_create.return_value = mock_content

        agent = GeneratorAgent()
        topic = _make_mock_topic(index=1)
        prev_summary = "We learned about forces and motion"

        asyncio.run(
            agent.generate_explanation(
                topic=topic,
                prev_summary=prev_summary,
                llm_context=LLMContext(api_key="test-key"),
            )
        )

        # Verify prev_summary appears in the user message
        call_kwargs = mock_create.call_args.kwargs
        user_message = call_kwargs["messages"][0]["content"]
        self.assertIn(prev_summary, user_message)
        self.assertIn("Previous Topic Summary", user_message)

    @patch(
        "server.agents.base.instructor_client.create_structured",
        new_callable=AsyncMock,
    )
    def test_context_injection_includes_next_summary(
        self, mock_create: AsyncMock
    ) -> None:
        """Positive test: Verify next_summary is included in user message.

        This test meets the objective by checking that next topic
        context is properly injected for foreshadowing.
        """
        import asyncio

        mock_content = _make_mock_content()
        mock_create.return_value = mock_content

        agent = GeneratorAgent()
        topic = _make_mock_topic(index=0)
        next_summary = "We will explore acceleration next"

        asyncio.run(
            agent.generate_explanation(
                topic=topic,
                next_summary=next_summary,
                llm_context=LLMContext(api_key="test-key"),
            )
        )

        # Verify next_summary appears in the user message
        call_kwargs = mock_create.call_args.kwargs
        user_message = call_kwargs["messages"][0]["content"]
        self.assertIn(next_summary, user_message)
        self.assertIn("Next Topic Summary", user_message)

    @patch(
        "server.agents.base.instructor_client.create_structured",
        new_callable=AsyncMock,
    )
    def test_first_topic_has_entry_point_message(self, mock_create: AsyncMock) -> None:
        """Positive test: First topic (no prev) gets entry point instructions.

        This test meets the objective by verifying that when there's
        no previous topic, appropriate entry point messaging is used.
        """
        import asyncio

        mock_content = _make_mock_content()
        mock_create.return_value = mock_content

        agent = GeneratorAgent()
        topic = _make_mock_topic(index=0)

        asyncio.run(
            agent.generate_explanation(
                topic=topic,
                prev_summary=None,  # First topic
                next_summary="Next topic info",
                llm_context=LLMContext(api_key="test-key"),
            )
        )

        call_kwargs = mock_create.call_args.kwargs
        user_message = call_kwargs["messages"][0]["content"]
        self.assertIn("first topic", user_message.lower())


class TestGeneratorAgentImport(unittest.TestCase):
    """Tests for module-level imports and exports."""

    def test_generator_agent_singleton_exists(self) -> None:
        """Verify the singleton instance is created."""
        self.assertIsNotNone(generator_agent)
        self.assertIsInstance(generator_agent, GeneratorAgent)

    def test_generated_content_model_exists(self) -> None:
        """Verify GeneratedContent model is exported."""
        content = _make_mock_content()
        self.assertIsNotNone(content.content_markdown)
        self.assertIsInstance(content.key_takeaways, list)


if __name__ == "__main__":
    unittest.main()
